config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :groups do
    resources :events
  end

  resources :users do
    resources :workouts
    resources :events
    resources :posts
    resources :comments
  end


  get "/" => "groups#home"
  get "/home" => "groups#home"
  get "/getevents" => "groups#getevents"
  get "/adduser" => "users#add"

end

app/models/group.rb
class Group < ApplicationRecord

  belongs_to :user
  has_many :user_groups
  has_many :users, through: :user_groups
  has_many :events, as: :happenings
  has_many :posts


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :set_group, only: [:show, :edit, :update, :destroy]

  # ======= GET / =======
  def index
    puts "\n******* index *******"

		@all_users = User.all
		if params[:search]
			@all_users = User.search(params[:search]).order("created_at DESC")
		else
			@all_users = User.all.order('created_at DESC')
		end

  end

  def home
    puts "\n******* home *******"
    @groups = Group.all
    @usergroup = current_user.groups
    puts "@usergroup: #{@usergroup.inspect}"
		puts "current_user: #{current_user.inspect}"

		@all_users = User.all
		if params[:search]
			@all_users = User.search(params[:search]).order("created_at DESC")
		else
			@all_users = User.all.order('created_at DESC')
		end
  end


  def show
    puts "\n******* show_group *******"
    @group = Group.find(params[:id])
    # puts "@group: #{@group.inspect}"
    @users = @group.users
    # puts "@users: #{@users.inspect}"
    @events = Event.where(group_id: @group)
    # puts "\n****** @events: #{@events.inspect}"
		@posts = @group.posts
		# puts "@posts: #{@posts.inspect}"
		@post = Post.new
		@comments = Comment.where(post_id: @posts)
		@comment = Comment.new

  end

def getevents
	puts "\n******* getevents *******"
	puts "params: #{params.inspect}"
	@group = Group.find(params[:group_id])
	@events = Event.where(group_id: @group)

	respond_to do |format|
		format.json {render :json => @events}
	end
end

def new
	puts "\n******* new_group *******"
	@group = Group.new
end

def create
	puts "\n******* create_group *******"

	@group = Group.new(group_params)
	if @group.save
		flash[:notice] = "Successfully created group."
		UserGroup.create(user_id: current_user.id, group_id: @group.id, user_type: "Group Leader" )
		redirect_to "/"
	end
end

private
  def set_group
    puts "******* set_params *******"
    @group = Group.find(params[:id])
  end

	def group_params
		puts "******* group_params *******"
		params.require(:group).permit(:group_name, :user_id, :group_type, :group_goal)
	end

end

app/views/groups/_calendar.html.erb
<%= link_to "New Event", new_user_event_path(current_user) %> <br />

<div id="calendar"></div>

app/views/groups/_form.html.erb
<div class="ui raised teal segment", id="creategroupForm">
  <h2> Create a New Group </h2><br>
  <%= form_for @group, :html => {:class => 'ui form'} do |f| %>
    <div class="field">
      <%= f.text_field :group_name, autofocus: true, placeholder: "Give Your Group a Name." %>
    </div>
      <%= f.hidden_field :user_id, value: current_user.id %>
    <div class="field">
      <%= f.text_field :group_type, autofocus: true, placeholder: "Give Your Group a Type. i.e. Weekly" %>
    </div>
    <div class="field">
      <%= f.text_field :group_goal, autofocus: true, placeholder: "What's Your Group Goal?" %>
    </div>

    <div class="actions">
      <%= f.submit "Submit", class: "ui basic teal button", id: "newgroupButton" %>
    </div>
  <% end %>
</div>

app/views/groups/_menu.html.erb
<% if current_user %>
  <div class="menuBar">

    <a href="/home">
      <div class="menuButtons" id="menuButtonHome">
        <button class="ui big animated fade inverted button" tabindex="0">
          <div class="visible content">
            <i class="home icon"></i>
          </div>
          <div class="hidden content">
            Home
          </div>
        </button>
      </div>
    </a>

    <a href="/groups/new">
      <div class="menuButtons" id="menuButtonNewGroup">
        <button class="ui big animated fade inverted button" tabindex="0">
          <div class="visible content">
            <i class="users icon"></i>
          </div>
          <div class="hidden content">
            Group
          </div>
        </button>
      </div>
    </a>

    <div class="menuButtons" id="menuButtonWorkout">
      <button class="ui big animated fade inverted button" tabindex="0">
        <div class="visible content">
          <i class="write icon"></i>
        </div>
        <div class="hidden content">
          <%= link_to "Workout", new_user_workout_path(current_user.id) %><br>
        </div>
      </button>
    </div>

    <%= form_tag(users_path, :method => "get", :class => "ui left icon input", :id => "menuSearch" ) do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Buddies" %>
      <i class="search icon"><br></i>
    <% end %>

    <div class="menuButtons" id="menuButtonSignout">
      <button class="ui big animated fade inverted button" tabindex="0">
        <div class="visible content">
          <i class="remove icon"></i>
        </div>
        <div class="hidden content">
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        </div>
      </button>
    </div>

    <a href="/users/edit">
      <div class="menuButtons" id="menuButtonEditUser">
        <button class="ui big animated fade inverted button" tabindex="0">
          <div class="visible content">
            <i class="edit icon"></i>
          </div>
          <div class="hidden content">
            Profile
          </div>
        </button>
      </div>
    </a>

  </div>
<% end %> </br>

app/views/groups/_results.html.erb
<p>Search Results</p>

<% @all_users.each do |user| %>
  <%= user.first_name %>
  <%= user.last_name %>
  <%= user.email %>
  <%= user.personal_bio %><br>

<% end %><br>

app/views/groups/home.html.erb
<div class="homeTitle">
  <p>TrainingBuddies.</p>
</div>

<%= render :partial => "menu" %>
<p id="welcomeMessage">Hello <%= current_user.first_name %>!</p>

<div class="ui raised teal segment", id="showgroupForm">

  <p id="userIntro"><%= current_user.first_name %>' Groups:</p>
    <% @usergroup.each do |g| %>
      <div class="ui list" id="groupList">
        <div class="item">
          <i class="large sun middle aligned icon"></i>
          <div class="content">
            <p><%= link_to g.group_name, group_path(g) %></p>
          </div>
        </div>
      </div></br>
    <% end %>
  </br>
</div>



<!-- /*<style>
  body {
    background-image: url("<%=image_path('DSC_0440.NEF.jpg')%>");
    background-position: center;
    background-attachment: fixed;
    background-size: 100%;
    background-repeat: no-repeat;
  }
</style>*/ -->

app/views/groups/index.html.erb
<h1>GROUPS index</h1>

app/views/groups/new.html.erb
<div class="homeTitle">
  <p>TrainingBuddies.</p>
</div>

<button class="ui basic teal button" id="backLink">
  <%= link_to 'Back', :back %>
</button>

<a href="/home">
  <button class="ui basic teal button" id="homeLink">Home</button>
</a>
<%= render :partial => "form" %>

app/views/groups/show.html.erb
<div class="homeTitle">
  <p>TrainingBuddies.</p>
</div>

<%= render :partial => "menu" %>


<!--+++++++ group info +++++++-->
<div class="ui raised teal segment" id="groupInfo">
  <p><%= @group.group_name %></p>

  <div class="ui raised segment" id="groupmainOther">
    Group Created By:
    <%= User.find(@group.user_id).first_name %><br>
    Group Type:
    <%= @group.group_type %><br>
    Group Goal:
    <%= @group.group_goal %><br>

    <div id="groupinfo">
      <p>Group Members:</p>
      <% @users.each do |user| %>
        <%= user.first_name %></br>
      <% end %><br />
    </div>
  </div></br>

</div>

<!--+++++++ events +++++++-->

<div class="ui raised segment" id="calContainer">
  <%= render :partial => "calendar" %>
</div>

<!--+++++++ create posts +++++++-->
<div class="ui raised segment" id="messBoard">


  <div class="ui big horizontal divided list" id="messageHead">
    <div class="item">
      <i class="huge comments blue icon"></i>
      <div class="content">
        <div class="header">Messages</div>
      </div>
    </div>
  </div>

  <%= form_for [current_user, @post], :html => {:class => 'ui form', :id => 'messageForm'} do |f| %>
    <div class="field">
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :group_id, {value: @group.id, id: "groupID"}  %>
      <%= f.text_field :title, placeholder: "Title" %>
    </div>
    <div class="field">
      <%= f.text_area :content, placeholder: "Share with your Buddies" %>
    </div>
    <div class="actions">
      <%= f.submit "Submit", class: "ui basic teal button", id: "postButton" %>
    </div>


  <% end %>

  <!--+++++++ show posts +++++++-->

  <% @posts.each do |post| %>
    <div class="ui raised teal segment" id="post">

      <%= User.find(post.user_id).first_name %></br>
      <%= post.title %><br>
      <%= post.content %>

      <!--+++++++ comments +++++++-->
      <div class="ui raised blue segment">
        <div class="content">
          <% @comments.each do |comment| %>
            <% if comment.post_id == post.id %>
              <a class="author">
                <%= User.find(comment.user_id).first_name %></br>
              </a>
              <div class="text">
                <%= comment.content %></br>
              </div>
            <% end %>

          <% end %></br>
        <!--+++++++ create comments +++++++-->

          <%= form_for [current_user, @comment], :html => {:class => 'ui reply form', :id => 'commentForm'} do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :post_id, value: post.id %>
            <div class="field" id="commentfield">
                <%= f.text_field :content, autofocus: true, placeholder: "Leave a Comment" %>
            </div>
            <div class="actions">
              <%= f.submit "Submit", class: "ui basic teal button", id: "commentButton" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>